Repository MapStory/story-tools-composer, pull requests merged in 2018-04, with the labels that each got.

#95 Fixes an issue in the regex that was stopping the slug from properly …
  app/state/stateSvc.js
Labels: in progress

#115 Setup story publishing and alert the user that their story has been p…
  app/state/stateSvc.js
  app/ui/composerController.js
  app/ui/templates/header.html
  app/ui/templates/storyPublished.html
Labels: in progress

#122 This PR resolves issues: 87, 93, 105
  app/frames/style/frames.less
  app/ui/composerController.js
  app/ui/templates/frames.html
Labels: Composer, bug, in progress

#128 Add CSS rule to hide full-screen button
  app/time/style/time.less
Labels: in progress

#127 Fix 125
  app/state/stateSvc.js
Labels: in progress

#130 Resolve form population issue
  app/ui/templates/chapterInfo.html
Labels: in progress

#132 Fix disappearing basemap
  app/state/stateSvc.js
Labels: in progress

#135 Build story layers on load from map ID
  app/map/mapManager.js
  app/state/configSvc.js
  app/state/stateSvc.js
Labels: in progress

#136 Issue 92: Fetch saved StoryFrames from API
  app/frames/style/frames.less
  app/state/stateSvc.js
  app/ui/composerController.js
  app/ui/templates/frames.html
Labels: in progress

#137 Fixes issue for moving storypins when changing chapters.
  app/pins/pinSvc.js
Labels: in progress

#139 Fixes GenerateThumbnail Location
  app/state/stateSvc.js
Labels: in progress

#141 Resurrected 92 fetch saved frames
  app/state/stateSvc.js
  app/ui/composerController.js
Labels: in progress

#142 Resolve Persistence & Thumbnail Issues
  app/state/stateSvc.js
  app/ui/composerController.js
Labels: in progress

#138 Add category picker to the Composer Story Info Modal.
  app/state/configSvc.js
  app/state/stateSvc.js
  app/ui/templates/storyInfoModal.html
Labels: in progress

#143 Add tooltip for creating StoryFrames
  app/ui/templates/frames.html
Labels: in progress

#148 Save basemap
  app/layers/layerList.js
  app/state/configSvc.js
  app/state/stateSvc.js
Labels: Review PR

#155 Issue 144: Edit StoryFrames button should set form to visible if hidden
  app/ui/composerController.js
  app/ui/templates/frames.html
  app/ui/templates/sidebar.html
Labels: bug, enhancement
